version: '3.8'

services:
  web:
    build: .
    volumes:
      - ./rates/:/usr/src/app/
    ports:
      - 3000:3000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    image: postgres:13.5-alpine
    networks:
    - default
    ports:
    - 5404:5432       # 5432 was already occupied in my host and I wanted to test it.
    restart: always
    volumes:
    - ./postgres-data:/var/lib/postgresql/data
    - ./db/rates.sql:/docker-entrypoint-initdb.d/rates.sql
